name: Setup Node
description: Setup Node.js environment and install dependencies
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
    - name: Install dependencies
      run: pnpm install
      shell: bash
