import s from './utility.module.css';

const color = {
  foreground: {
    white: s['foreground-white'],
    'white-secondary': s['foreground-white-secondary'],
    theme: s['foreground-theme'],
    'theme-secondary': s['foreground-theme-secondary'],
    contrast: s['foreground-contrast'],
    'on-contrast': s['foreground-on-contrast'],
    'contrast-secondary': s['foreground-contrast-secondary'],
    'contrast-tertiary': s['foreground-contrast-tertiary'],
    error: s['foreground-error'],
    'error-secondary': s['foreground-error-secondary'],
    'error-tertiary': s['foreground-error-tertiary'],
    'error-less': s['foreground-error-less'],
    success: s['foreground-success'],
    'success-less': s['foreground-success-less'],
    'success-secondary': s['foreground-success-secondary'],
    warning: s['foreground-warning'],
    'warning-secondary': s['foreground-warning-secondary'],
    visited: s['foreground-visited'],
  },
};

const typography = {
  'display-big': s['display-big'],
  'display-normal': s['display-normal'],
  'display-compact': s['display-compact'],
  'display-big-strong': s['display-big-strong'],
  'display-normal-strong': s['display-normal-strong'],
  'display-compact-strong': s['display-compact-strong'],
  headline: s.headline,
  title: s.title,
  subheading: s.subheading,
  'text-big': s['text-big'],
  'text-big-strong': s['text-big-strong'],
  'text-big-medium': s['text-big-medium'],
  'text-normal': s['text-normal'],
  'text-normal-strong': s['text-normal-strong'],
  'text-normal-medium': s['text-normal-medium'],
  'text-compact': s['text-compact'],
  'text-compact-strong': s['text-compact-strong'],
  'text-compact-medium': s['text-compact-medium'],
  'caps-big': s['caps-big'],
  'caps-big-strong': s['caps-big-strong'],
  'caps-normal': s['caps-normal'],
  'caps-normal-strong': s['caps-normal-strong'],
  'caps-compact': s['caps-compact'],
  'caps-compact-strong': s['caps-compact-strong'],
  'mono-big': s['mono-big'],
  'mono-big-strong': s['mono-big-strong'],
  'mono-normal': s['mono-normal'],
  'mono-normal-strong': s['mono-normal-strong'],
  'mono-compact': s['mono-compact'],
  'mono-compact-strong': s['mono-compact-strong'],
  'mono-codeblock': s['mono-codeblock'],
  'tabular-big': s['tabular-big'],
  'tabular-big-strong': s['tabular-big-strong'],
  'tabular-normal': s['tabular-normal'],
  'tabular-normal-strong': s['tabular-normal-strong'],
  'tabular-compact': s['tabular-compact'],
  'tabular-compact-strong': s['tabular-compact-strong'],
  'italic-big': s['italic-big'],
  'italic-big-strong': s['italic-big-strong'],
  'italic-normal': s['italic-normal'],
  'italic-normal-strong': s['italic-normal-strong'],
  'italic-compact': s['italic-compact'],
  'italic-compact-strong': s['italic-compact-strong'],
  inherit: s.inherit,
};

export const utilClasses = {
  hideVisually: s['hide-visually'],
  color,
  typography,
  list: s.list,
  listItem: s['list-item'],
};
