name: '🐞 Bug report'
description: Report a bug, it will help improve our library

title: 'Bug: (fill in)'
labels:
  - bug

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A description and a picture of what the bug looks like.
    validations:
      required: true

  - type: textarea
    id: bug-playback
    attributes:
      label: How to make the bug happen
      description: Step-by-step description to make the bug happen.
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe the expected behavior.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Library version
      description: Please provide version.
      placeholder: 0.0.1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know?

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following.
      options:
        - label: Read the [docs](https://react.koobiq.io/).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/koobiq/react-components/issues) that reports the same bug to avoid creating a duplicate.
          required: true
