name: '🚀 Propose an improvement'
description: Propose a improvement to be added to the library

title: 'Feature: (fill in)'
labels:
  - enhancement

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: What should the feature do?
    validations:
      required: true

  - type: textarea
    id: feature-behavior
    attributes:
      label: Expected behavior
      description: Describe the behavior of the feature.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know?

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following.
      options:
        - label: Read the [docs](https://react.koobiq.io/).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/koobiq/react-components/issues) that reports the same bug to avoid creating a duplicate.
          required: true
