export default {
  'ru-RU': {
    emptyTitle: 'Перетащите сюда',
    listEmptyText: 'Перетащите сюда',
    dropOverlayTitle: 'Перетащите сюда',
    addMoreText: 'Перетащите ещё',
    alternativeSeparator: 'или',
    browseFile: 'выберите файл',
    browseFiles: 'выберите файлы',
    browseFolder: 'выберите папку',
    browseFilesOrFolder: 'выберите файлы или папку',
    browseFolderMixed: 'папку',
    removeButtonLabel: 'Удалить',
    bytesUnit: 'Б',
    kilobytesUnit: 'КБ',
    megabytesUnit: 'МБ',
    gigabytesUnit: 'ГБ',
    terabytesUnit: 'ТБ',
  },
  'en-US': {
    emptyTitle: 'Drag here',
    listEmptyText: 'Drag here',
    dropOverlayTitle: 'Drag here',
    addMoreText: 'Drop more',
    alternativeSeparator: 'or',
    browseFile: 'select a file',
    browseFiles: 'select files',
    browseFolder: 'select a folder',
    browseFilesOrFolder: 'select files or a folder',
    browseFolderMixed: 'a folder',
    removeButtonLabel: 'Remove',
    bytesUnit: 'B',
    kilobytesUnit: 'KB',
    megabytesUnit: 'MB',
    gigabytesUnit: 'GB',
    terabytesUnit: 'TB',
  },
} as unknown as Record<string, Record<string, string>>;
