export default {
  'ru-RU': {
    dropHere: 'Перетащите сюда',
    dropTitle: 'Перетащите файлы сюда',
    or: 'или',
    browseFile: 'выберите файл',
    browseFiles: 'выберите файлы',
    browseFolder: 'выберите папку',
    browseFilesOrFolder: 'выберите файлы или папку',
    addMore: 'Перетащите ещё или',
    removeButtonLabel: 'Удалить',
    uploadingLabel: 'Загрузка…',
    bytes: 'Б',
    kilobytes: 'КБ',
    megabytes: 'МБ',
    gigabytes: 'ГБ',
    terabytes: 'ТБ',
  },
  'en-US': {
    dropHere: 'Drop files here',
    dropTitle: 'Drop files here',
    or: 'or',
    browseFile: 'select a file',
    browseFiles: 'select files',
    browseFolder: 'select a folder',
    browseFilesOrFolder: 'select files or a folder',
    addMore: 'Drop more or',
    removeButtonLabel: 'Remove',
    uploadingLabel: 'Uploading…',
    bytes: 'B',
    kilobytes: 'KB',
    megabytes: 'MB',
    gigabytes: 'GB',
    terabytes: 'TB',
  },
} as unknown as Record<string, Record<string, string>>;
