import type { Columns, Rows } from './types';

export const columns: Columns = [
  { name: 'Component', key: 'component' },
  { name: 'Status', key: 'status' },
  { name: 'Planned (Quarter)', key: 'planned' },
  { name: 'Stage', key: 'stage' },
];

export const rows: Rows = [
  {
    component: 'Provider',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Typography',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q4 2024',
  },
  {
    component: 'Icons',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q4 2024',
  },
  {
    component: 'Button',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'IconButton',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Badge',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q4 2024',
  },
  {
    component: 'Link',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Checkbox',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Radio, RadioGroup',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Toggle',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Input',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Textarea',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2024',
  },
  {
    component: 'Alert',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q4 2024',
  },
  {
    component: 'Grid',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'Container',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'ProgressBar',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'ProgressSpinner',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'InputNumber',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'Backdrop',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'Dialog',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'Modal',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'SidePanel',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'FlexBox',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'SkeletonBlock',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'SkeletonTypography',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q1 2025',
  },
  {
    component: 'Popover',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'Tooltip',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'List',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'AnimatedIcon',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'Select',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q1 2025',
  },
  {
    component: 'Divider',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q2 2025',
  },
  {
    component: 'Menu',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q2 2025',
  },
  {
    component: 'ButtonToggleGroup',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q2 2025',
  },
  {
    component: 'TagGroup',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q2 2025',
  },
  {
    component: 'Table',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q2 2025',
  },
  {
    component: 'Calendar',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q2 2025',
  },
  {
    component: 'RouterProvider',
    status: '✅ Done',
    stage: '🟢 stable',
    planned: 'Q3 2025',
  },
  {
    component: 'DateInput',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q3 2025',
  },
  {
    component: 'DatePicker',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q3 2025',
  },
  {
    component: 'TimePicker',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q3 2025',
  },
  {
    component: 'Select (multiple)',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q3 2025',
  },
  {
    component: 'SearchInput',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q3 2025',
  },
  {
    component: 'Form',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q3 2025',
  },
  {
    component: 'Tabs',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2025',
  },
  {
    component: 'Autocomplete',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2025',
  },
  {
    component: 'CheckboxGroup',
    status: '✅ Done',
    stage: '🔵 experimental',
    planned: 'Q4 2025',
  },
  { component: 'Breadcrumbs', status: '🚧 Planned', planned: 'Q4 2025' },
  { component: 'Toast', status: '🚧 Planned', planned: 'Q4 2025' },
  { component: 'ActionPanel', status: '🚧 Planned', planned: 'Q4 2025' },
  { component: 'Collapse', status: '🚧 Planned', planned: 'Q4 2025' },
  { component: 'Accordion', status: '🚧 Planned', planned: 'Q4 2025' },
  { component: 'Tree', status: '🚧 Planned', planned: 'Q4 2025' },
];
