name: Linters

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - name: Type check
        run: pnpm run type-check
      - name: Check formatting
        run: pnpm run format:check
      - name: Lint CSS
        run: pnpm run lint:css --max-warnings=0
      - name: Lint JS
        run: pnpm run lint:js --max-warnings=0
