name: Pull Request Notification

on:
  pull_request_target:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TEXT: |
        [${{ github.repository }}] | [${{ github.event.pull_request.title }} #${{ github.event.number }}](https://github.com/${{ github.repository }}/pull/${{ github.event.number }}) was created by ${{ github.actor }}
    steps:
      - name: Notification to main channel
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: ${{ secrets.MM_CHANNEL_NAME }}
          MATTERMOST_USERNAME: ${{ secrets.MM_BOT_NAME }}
          TEXT: ${{ env.TEXT }}

      - name: Notification to dev channel
        uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: ${{ secrets.MM_CHANNEL_BOT_PR }}
          MATTERMOST_USERNAME: ${{ secrets.MM_BOT_NAME }}
          TEXT: ${{ env.TEXT }}
