name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run: |
          pnpm run test --run
